name: Auto merge

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - id: vars
        run: |
          echo "owner=$(gh pr view --json headRepositoryOwner --jq .headRepositoryOwner.login)" >> "$GITHUB_OUTPUT"
          echo "repo=$(gh pr view --json headRepository --jq .headRepository.name)" >> "$GITHUB_OUTPUT"
          echo "ref=$(gh pr view --json headRefName --jq .headRefName)" >> "$GITHUB_OUTPUT"
      - name: "Merge pull request"
        if: steps.vars.outputs.ref == 'changeset-release/main' && steps.vars.outputs.owner == 'lukasbach' && steps.vars.outputs.repo == 'headless-tree'
        uses: "actions/github-script@v6"
        with:
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            await github.rest.pulls.merge({
              merge_method: "squash",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })