name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: volta-cli/action@v3
        with:
          always-auth: true
          registry-url: https://registry.npmjs.org/
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn
      - run: yarn lint
      - run: yarn build:core
      - run: yarn docs
      - run: yarn docs:md
      - run: yarn build:web
      - run: yarn changeset version
      - run: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      # - uses: changesets/action@v1.4.0
      #   id: changesets
      #   with:
      #     publish: yarn changeset publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: publish
      #   if: steps.changesets.outputs.hasChangesets == 'false'
      #   run: yarn changeset publish
