name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: yarn
      - run: yarn lint
      - run: yarn build:core
      - run: yarn docs
      - run: yarn docs:md
      - run: yarn build:web
      - name: changesets
        id: changesets
        uses: changesets/action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: yarn changeset publish
