name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ./.yarn/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
      - uses: volta-cli/action@v3
      - run: yarn
      - run: yarn lint:test
      - run: yarn build:core
      - run: yarn docs
      - run: yarn docs:md
      - run: yarn build:web
      - run: yarn changeset version
      - run: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          message: "chore: release [skip ci]"
          tags: true
